/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "fulladder.v:7.1-16.10" *)
module full_adder(A, B, Cin, S, Cout);
  (* src = "fulladder.v:8.11-8.12" *)
  wire _00_;
  (* src = "fulladder.v:9.11-9.12" *)
  wire _01_;
  (* src = "fulladder.v:10.11-10.14" *)
  wire _02_;
  (* src = "fulladder.v:12.12-12.16" *)
  wire _03_;
  (* src = "fulladder.v:11.12-11.13" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "fulladder.v:15.33-15.42" *)
  wire _09_;
  (* src = "fulladder.v:15.45-15.48" *)
  wire _10_;
  (* src = "fulladder.v:15.38-15.41" *)
  wire _11_;
  (* src = "fulladder.v:15.24-15.27" *)
  wire _12_;
  (* src = "fulladder.v:8.11-8.12" *)
  input A;
  wire A;
  (* src = "fulladder.v:9.11-9.12" *)
  input B;
  wire B;
  (* src = "fulladder.v:10.11-10.14" *)
  input Cin;
  wire Cin;
  (* src = "fulladder.v:12.12-12.16" *)
  output Cout;
  wire Cout;
  (* src = "fulladder.v:11.12-11.13" *)
  output S;
  wire S;
  assign _06_ = _01_ | _00_;
  assign _07_ = _02_ & _06_;
  assign _08_ = _01_ & _00_;
  assign _03_ = _07_ | _08_;
  assign _05_ = _01_ ^ _00_;
  assign _04_ = _02_ ^ _05_;
  assign _01_ = B;
  assign _00_ = A;
  assign _02_ = Cin;
  assign Cout = _03_;
  assign S = _04_;
endmodule
