/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "halfadder.v:7.1-14.10" *)
module half_adder(A, B, SUM, CARRY);
  (* src = "halfadder.v:8.11-8.12" *)
  wire _0_;
  (* src = "halfadder.v:9.11-9.12" *)
  wire _1_;
  (* src = "halfadder.v:11.12-11.17" *)
  wire _2_;
  (* src = "halfadder.v:10.12-10.15" *)
  wire _3_;
  (* src = "halfadder.v:8.11-8.12" *)
  input A;
  wire A;
  (* src = "halfadder.v:9.11-9.12" *)
  input B;
  wire B;
  (* src = "halfadder.v:11.12-11.17" *)
  output CARRY;
  wire CARRY;
  (* src = "halfadder.v:10.12-10.15" *)
  output SUM;
  wire SUM;
  assign _2_ = _0_ & _1_;
  assign _3_ = _0_ ^ _1_;
  assign _0_ = A;
  assign _1_ = B;
  assign CARRY = _2_;
  assign SUM = _3_;
endmodule
